[functions.manage-token]
enabled = true
verify_jwt = false
entrypoint = "./functions/manage-token/index.ts"

[functions.send-individual]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-individual/index.ts"

[functions.schedule-batch]
enabled = true
verify_jwt = false
entrypoint = "./functions/schedule-batch/index.ts"

[functions.process-batches]
enabled = true
verify_jwt = false
entrypoint = "./functions/process-batches/index.ts"

[functions.delete-user]
enabled = true
verify_jwt = true
import_map = "./functions/delete-user/deno.json"
entrypoint = "./functions/delete-user/index.ts"

[functions.maybe-hardbounced]
enabled = true
verify_jwt = false
entrypoint = "./functions/maybe-hardbounced/index.ts"

[functions.track-open-v2]
enabled = true
verify_jwt = false

[functions.track-click-v2]
enabled = true
verify_jwt = false

[functions.cleanup-old-files]
enabled = true
verify_jwt = false